<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Thread extends Model
{
    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope("replyCount", function ($builder) {

            $builder->withCount("replies");

        });
    }

    public function path()
    {

        return "/threads/foobar/{$this->id}";
    }

    public function replies()
    {

        return $this->hasMany(Reply::class)
            ->withCount('favorites')->with('owner');

    }

    function creator()
    {

        return $this->belongsTo('App\User', 'user_id');

    }

    public function channel()
    {
        return $this->belongsTo(Channel::class);
    }

    function addReply($reply)
    {

        $this->replies()->create($reply);

    }

    function scopeFilter($query, $filters)
    {

        return $filters->apply($query);

    }

}
